---

- name: Transfer sysconfig/docker file
  template:
    src: sysconfig-docker.j2
    dest: /etc/sysconfig/docker
    owner: root
    group: root
    mode: '0644'
  notify: restart docker

- name: Transfer sysconfig/docker-storage-setup file
  template:
    src: sysconfig-docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: '0644'
  when: docker_lvm_disk is defined

- name: Create docker group
  group:
    name: docker
    state: present
    system: yes
  notify: restart docker

- name: Add admin users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_admin_users }}"
  notify: restart docker
