---

- name: Enable and start LVM metadata service (lvmetad)
  service:
    name: lvm2-lvmetad
    enabled: yes
    state: started
  when: docker_lvm_disk is defined

- name: Enable and start service
  service:
    name: docker
    enabled: yes
    state: started
