---

- name: Import PGP key
  rpm_key:
    key: https://yum.dockerproject.org/gpg
    state: present

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ docker_packages[docker_version] }}"

- name: Installing extra dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items: docker_dependencies

- name: Transfer sysconfig/docker file
  copy:
    src: sysconfig-docker
    dest: /etc/sysconfig/docker
    owner: root
    group: root
    mode: '0644'
  notify: restart docker

- name: Configure systemd service
  copy:
    src: docker.service
    dest: /usr/lib/systemd/system/docker.service
    owner: root
    group: root
    mode: '0644'
  notify: 
    - reload systemd
    - restart docker

- name: Enable and start service
  service:
    name: docker
    enabled: yes
    state: started
